site_name: Lorrana
theme:
    name: readthedocs
    highlightjs: true
site_url: https://rafaelleone.github.io/mkdocs_curriculo/
repo_url: https://github.com/RafaelLeone/mkdocs_curriculo
nav:
    - Início: 'index.md'