site_name: Lorrana
theme:
    name: readthedocs
    highlightjs: true
site_url: https://lorrananeves/mkdocs_curriculo/
repo_url: https://github.com/lorrananeves/mkdocs_curriculo
nav:
    - Início: 'index.md'
